pgallery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,
        {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,
        {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', include('picapp.urls')),
    path('users/', include('users.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

picapp/urls.py
from django.urls import path

from .views import (
    AlbumCreateView,
    AlbumListView,
    PhotoListView,
    PhotoTagListView,
    PhotoDetailView,
    PhotoCreateView,
    PhotoUpdateView,
    PhotoDeleteView,
    AlbumUpdateView,
    AlbumDeleteView
)

app_name = 'photo'

urlpatterns = [
    path('', AlbumListView.as_view(), name='albums'),
    path('<slug:slug>', PhotoListView.as_view(), name='photos'),
    path('tag/<slug:tag>/', PhotoTagListView.as_view(), name='tag'),
    path('create_album/', AlbumCreateView.as_view(), name='create_album'),
    path('photo/<int:pk>/', PhotoDetailView.as_view(), name='detail'),
    path('photo/create/', PhotoCreateView.as_view(), name='create'),
    path('photo/<int:pk>/update/', PhotoUpdateView.as_view(), name='update'),
    path('photo/<int:pk>/delete/', PhotoDeleteView.as_view(), name='delete'),
    path('<slug>/update_album/', AlbumUpdateView.as_view(), name='update_album'),
    path('<slug>/delete_album/', AlbumDeleteView.as_view(), name='delete_album')
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import SignUpView, CustomLoginView

app_name = 'user'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

picapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from taggit.managers import TaggableManager
from autoslug import AutoSlugField
from django.urls import reverse
from imagekit.models import ImageSpecField
from pilkit.processors import Thumbnail
from django.core.exceptions import ValidationError
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFit


class Album(models.Model):

    def validate_image(fieldfile_obj):
        filesize = fieldfile_obj.file.size
        megabyte_limit = 5.0
        if filesize > megabyte_limit*1024*1024:
            raise ValidationError("Max file size is %sMB" %
                                  str(megabyte_limit))

    title = models.CharField(max_length=20)
    description = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    submitter = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    is_public = models.BooleanField(default=True, verbose_name="Public Album")
    slug = AutoSlugField(populate_from='title', unique=True)
    thumb = ProcessedImageField(upload_to='photos/', processors=[Thumbnail(
        400, 400)], format='JPEG', options={'quality': 90}, validators=[validate_image])

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('photos', kwargs={'slug': self.slug})


class Photo(models.Model):

    def validate_image(fieldfile_obj):
        filesize = fieldfile_obj.file.size
        megabyte_limit = 5.0
        if filesize > megabyte_limit*1024*1024:
            raise ValidationError("Max file size is %sMB" %
                                  str(megabyte_limit))

    title = models.CharField(max_length=20)
    description = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    image = ProcessedImageField(upload_to='photos/',
                                processors=[ResizeToFit(
                                    width=1024, upscale=False)],
                                format='JPEG',
                                options={'quality': 90},
                                validators=[validate_image])
    image_medium = ImageSpecField(source='image',
                                  processors=[Thumbnail(400, 400,)],
                                  format='JPEG',
                                  options={'quality': 90})
    submitter = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    tags = TaggableManager(blank=True)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    is_public = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('images', kwargs={'id': self.pk})

    def save(self, *args, **kwargs):
        self.is_public = Album.objects.get(title=self.album).is_public
        super().save(*args, **kwargs)

picapp/forms.py
from .models import Photo, Album
from django import forms


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ['title', 'description', 'image', 'tags', 'album']

    image = forms.FileField(
        widget=forms.ClearableFileInput(attrs={'multiple': True}))

    def __init__(self, *args, **kwargs):
        submitter = kwargs.pop('submitter')
        super(PhotoForm, self).__init__(*args, **kwargs)
        self.fields['album'].queryset = Album.objects.filter(
            submitter=submitter) | Album.objects.filter(is_public=True)


class AlbumForm(forms.ModelForm):

    class Meta:
        model = Album
        fields = ['title', 'description', 'thumb', 'is_public']
        help_texts = {
            'is_public': ('(Uncheck for private album)')}

picapp/views.py
from django.shortcuts import get_object_or_404
from django.core.exceptions import PermissionDenied
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from .models import Photo, Album
from .forms import PhotoForm, AlbumForm
from django import forms
from .filters import SnippetFilter


class AlbumListView(ListView):
    model = Album
    template_name = 'picapp/albums.html'
    context_object_name = 'albums'

    def get_queryset(self):
        if self.request.user.is_authenticated:
            return Album.objects.filter(is_public=False, submitter=self.request.user) | Album.objects.filter(is_public=True)
        else:
            return Album.objects.filter(is_public=True)


class AlbumUserIsAuthorized(UserPassesTestMixin):

    def get_album(self):
        return get_object_or_404(Album, slug=self.kwargs['slug'])

    def test_func(self):
        if self.request.user.is_authenticated:
            return self.request.user == self.get_album().submitter or self.get_album().is_public == True
        elif self.request.user.is_anonymous:
            return self.get_album().is_public == True
        else:
            raise PermissionDenied


class PhotoListView(AlbumUserIsAuthorized, ListView):

    template_name = 'picapp/photos.html'
    context_object_name = 'photos'

    def get_queryset(self):
        self.album = get_object_or_404(Album, slug=self.kwargs['slug'])
        if self.request.user.is_authenticated:
            return Photo.objects.filter(album=self.album) & (Photo.objects.filter(is_public=False, submitter=self.request.user) | Photo.objects.filter(is_public=True))
        else:
            return Photo.objects.filter(is_public=True) & Photo.objects.filter(album=self.album)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['album'] = self.album
        context['filter'] = SnippetFilter(
            self.request.GET, queryset=self.get_queryset())
        return context


class PhotoTagListView(ListView):

    template_name = 'picapp/taglist.html'
    context_object_name = 'tags'

    def get_tag(self):
        return self.kwargs.get('tag')

    def get_queryset(self):
        if self.request.user.is_authenticated:
            return Photo.objects.filter(tags__slug=self.get_tag()) & (Photo.objects.filter(is_public=False, submitter=self.request.user) | Photo.objects.filter(is_public=True))
        else:
            return Photo.objects.filter(is_public=True) & Photo.objects.filter(tags__slug=self.get_tag())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tag"] = self.get_tag()
        return context


class PhotoViewerIsAuthorized(UserPassesTestMixin):

    def get_photo(self):
        return get_object_or_404(Photo, id=self.kwargs['pk'])

    def test_func(self):
        if self.request.user.is_authenticated:
            return self.request.user == self.get_photo().submitter or self.get_photo().is_public == True
        elif self.request.user.is_anonymous:
            return self.get_photo().is_public == True
        else:
            raise PermissionDenied


class PhotoDetailView(PhotoViewerIsAuthorized, DetailView):

    model = Photo
    template_name = 'picapp/detail.html'
    context_object_name = 'photo'


class PhotoCreateView(LoginRequiredMixin, CreateView):

    form_class = PhotoForm
    template_name = 'picapp/create.html'

    def get_success_url(self):
        return reverse_lazy('photo:photos', kwargs={'slug': self.object.album.slug})

    def get_form_kwargs(self):
        kwargs = super(PhotoCreateView, self).get_form_kwargs()
        kwargs['submitter'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.instance.submitter = self.request.user
        return super().form_valid(form)


class AlbumCreateView(LoginRequiredMixin, CreateView):

    form_class = AlbumForm
    template_name = 'picapp/create_album.html'

    def form_valid(self, form):
        form.instance.submitter = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('photo:photos', kwargs={'slug': self.object.slug})


class UserIsSubmitter(UserPassesTestMixin):

    def get_photo(self):
        return get_object_or_404(Photo, pk=self.kwargs.get('pk'))

    def test_func(self):
        if self.request.user.is_authenticated:
            return self.request.user == self.get_photo().submitter
        else:
            raise PermissionDenied('Sorry.... Access denied!')


class UserIsAlbumSubmitter(UserPassesTestMixin):

    def get_album(self):
        return get_object_or_404(Album, slug=self.kwargs['slug'])

    def test_func(self):
        if self.request.user.is_authenticated:
            return self.request.user == self.get_album().submitter
        else:
            raise PermissionDenied('Sorry.... Access denied!')


class PhotoUpdateView(LoginRequiredMixin, UserIsSubmitter, UpdateView):

    model = Photo
    form_class = PhotoForm
    template_name = 'picapp/update.html'

    def get_success_url(self):
        return reverse_lazy('photo:photos', kwargs={'slug': self.object.album.slug})

    def get_form_kwargs(self):
        kwargs = super(PhotoUpdateView, self).get_form_kwargs()
        kwargs['submitter'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.instance.submitter = self.request.user
        return super().form_valid(form)


class PhotoDeleteView(LoginRequiredMixin, UserIsSubmitter, DeleteView):

    template_name = 'picapp/delete.html'
    model = Photo

    def get_success_url(self):
        return reverse_lazy('photo:photos', kwargs={'slug': self.object.album.slug})


class AlbumUpdateView(LoginRequiredMixin, UserIsAlbumSubmitter, UpdateView):

    model = Album
    form_class = AlbumForm
    template_name = 'picapp/update_album.html'

    def get_success_url(self):
        return reverse_lazy('photo:photos', kwargs={'slug': self.object.slug})

    def form_valid(self, form):
        form.instance.submitter = self.request.user
        return super().form_valid(form)


class AlbumDeleteView(LoginRequiredMixin, UserIsAlbumSubmitter, DeleteView):

    template_name = 'picapp/delete_album.html'
    model = Album
    success_url = reverse_lazy('photo:albums')

picapp/templates/picapp/albums.html
{% extends 'base.html' %}

{% block body %}
<div class="row">
  {% for album in albums %}
  <div id="photo" class="col-lg-3 col-md-4 col-xs-6">
    <div class="card">
      <a href="{% url 'photo:photos' album.slug %}" class="d-block mb-4 h-100"><img src="{{ album.thumb.url }}"
          class="card-img-top" alt="{{ album.title }}" /></a>
      <div id="card-body" class="card-body">
        <p class="card-title">{{ album.title }}</p>
        <p class="card-text">
          by {{ album.submitter }}
        </p>
        <!-- IF WANT ADD DETAILS
        <button type="button" class="collapsible_button">Show details</button>
        <div class="content_collasible">
          <p class="card-text">
            {{ album.description }} <br>
            {{ album.created|date:"d.m.Y H:i" }}
          </p>
          {% if user == album.submitter %}
          <div class="center">
            <div class="btn-group text-center">
              <a href="{% url 'photo:update_album' album.slug %}" class="btn btn-sm btn-outline-success">Update</a></span>
              <a href="{% url 'photo:delete_album' album.slug %}" class="btn btn-sm btn-outline-danger">Delete</a></span>
            </div>
          </div>
          {% endif %}
        </div> -->
      </div>
    </div>
  </div>
  {% empty %}
  <h2 class="text-center">There are no albums in this photo gallery yet!</h2>
  <p class="text-center">Maybe add some?</p>
  <div class="text-center">
    <a href="{% url 'photo:create_album' %}" class="btn btn-success btn-md">Click here!</a>
  </div>
  {% endfor %}
</div>
{% endblock body %}

picapp/templates/picapp/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
<div class="forms col-md-6 offset-md-3">
  <div class="mx-auto">
    <h1 class="mt-3 text-center">Add photo</h1>
  </div>
  <div class="form-group">
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.title|as_crispy_field}}<br>
      {{ form.description|as_crispy_field}}<br>
      {{ form.image|as_crispy_field}}<br>
      {{ form.tags|as_crispy_field}}<br>
      {{ form.album|as_crispy_field}}<br>
      <button type="submit" class="btn btn-success">Add Photo</button>
    </form>
  </div>
</div>
{% endblock body %}

picapp/templates/picapp/create_album.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
<div class="forms col-md-6 offset-md-3">
  <div class="mx-auto">
    <h1 class="mt-3 text-center">Add Album</h1>
  </div>
  <div class="form-group">
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.title|as_crispy_field}}<br>
      {{ form.description|as_crispy_field}}<br>
      {{ form.thumb|as_crispy_field}}<br>
      {{ form.is_public|as_crispy_field}}<br>
      <button type="submit" class="btn btn-success">Add Album</button>
    </form>
  </div>
</div>
{% endblock body %}

picapp/templates/picapp/delete.html
{% extends 'base.html' %}

{% block body %}
<div class="forms col-md-8 offset-md-2">
  <div class="form-group mx-auto">
    <h2 class="text-center">
      You are going to <span class="text-danger">delete</span>: <i>"{{ photo }}"</i></h2>
    <p class="text-center">Are you sure, you want to delete the photo?<br>This action is irreversible</p>
    <div class="form-group">
      <form action="" method="post" class="d-flex flex-column align-items-center justify-content-center">
        {% csrf_token %}
        <div class="row">
          <div class="col">
            <a href="{% url 'photo:albums' %}" class="btn btn-primary">Cancel</a>
          </div>
          <div class="col">
            <button type="submit" class="btn btn-danger">Delete</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock body %}

picapp/templates/picapp/delete_album.html
{% extends 'base.html' %}

{% block body %}
<div class="forms col-md-8 offset-md-2">
  <div class="form-group mx-auto">
    <h2 class="text-center">
      You are going to <span class="text-danger">delete</span>: <i>"{{ album }}"</i></h2>
    <p class="text-center">Are you sure, you want to delete the album?<br>This action is irreversible.</p>
    <div class="form-group">
      <form action="" method="post" class="d-flex flex-column align-items-center justify-content-center">
        {% csrf_token %}
        <div class="row">
          <div class="col">
            <a href="{% url 'photo:photos' album.slug %}" class="btn btn-primary">Cancel</a>
          </div>
          <div class="col">
            <button type="submit" class="btn btn-danger">Delete</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock body %}

picapp/templates/picapp/photos.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
<div class="row">
  <div class="col">
    <div class="ordering">
      <form method="GET" class="text-wrap" style="width: 7rem;">
        {{ filter.form|crispy }}
        <button type="submit" class="btn btn-outline-dark btn-sm my-1">Order by date</button>
      </form>
    </div>
  </div>
  <div class="col-6">
       <h2 class="text-center">{{album.title}}</h2>
    <p class="text-center fw-light">{{album.description}}<br>Created on: {{album.created|date:"d.m.Y H:i"}} <br> By
      {{album.submitter.username}}</p>
    {% if user == album.submitter %}
    <div class="center">
      <div class="btn-group text-center">
        <a href="{% url 'photo:update_album' album.slug %}" class="btn btn-sm btn-outline-success">Update</a></span>
        <a href="{% url 'photo:delete_album' album.slug %}" class="btn btn-sm btn-outline-danger">Delete</a></span>
      </div>
    </div>
    <br>
    {% endif %}
  </div>
  <div class="col">
  </div>
</div>
<section class="photo_gallery">
  <div class="row" id="sortable">
    {% for photo in filter.qs %}
    <div id="photo" class="col-lg-3 col-md-4 col-xs-6">
      <div class="card">
        <a id="lightbox" href="{{photo.image.url}}" class="d-block mb-4 h-100">
          <img src="{{photo.image_medium.url}}" class="card-img-top" alt="{{photo.title}}"
            title="{{photo.title|capfirst}} by {{photo.submitter}}">
        </a>
        <div id="card-body" class="card-body">
          <p class="card-title">{{ photo.title }}</p>
          <p class="card-text">
            by {{ photo.submitter }}
          </p>
          <button type="button" class="collapsible_button">Show details</button>
          <div class="content_collasible">
            <p class="card-text">
              {{ photo.description }} <br>
              {{ photo.created|date:"d.m.Y H:i" }}
            </p>
            {% for tag in photo.tags.all %}
            <a class="tags" href="{% url 'photo:tag' tag.slug %}">#{{ tag.name }}&nbsp;</a>
            {% endfor %}
            {% if user == photo.submitter %}
            <div class="center">
              <div class="btn-group">
                <a href="{% url 'photo:update' photo.id %}" class="btn btn-sm btn-outline-success">Update</a>
                <a href="{% url 'photo:delete' photo.id %}" class="btn btn-sm btn-outline-danger">Delete</a>
              </div>
            </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
    {% empty %}
    <h2 class="text-center">There are no photos in this album yet!</h2>
    <p class="text-center">Maybe add some?</p>
    <div class="text-center">
      <a href="{% url 'photo:create' %}" class="btn btn-success btn-md">Click here!</a>
    </div>
    {% endfor %}
  </div>
</section>
<br>

{% endblock body %}

picapp/templates/picapp/taglist.html
{% extends 'base.html' %}

{% block body %}
<div class="alert alert-secondary">
  <h2 class="text-center">Photos with the tag {{tag}}</h2>
</div>
<section class="photo_gallery">
  <div class="row" id="sortable">
    {% load shuffle %}
    {% for photo in tags|shuffle %}
    <div id="photo" class="col-lg-3 col-md-4 col-xs-6">
      <div class="card">
        <a id="lightbox" href="{{photo.image.url}}" class="d-block mb-4 h-100">
          <img src="{{photo.image_medium.url}}" class="card-img-top" alt="{{photo.title}}"
            title="{{photo.title|capfirst}} by {{photo.submitter}}">
        </a>
        <div id="card-body" class="card-body">
          <p class="card-title">{{ photo.title }}</p>
          <p class="card-text">
            by {{ photo.submitter }}
          </p>
          <button type="button" class="collapsible_button">Show details</button>
          <div class="content_collasible">
            <p class="card-text">
              {{ photo.description }} <br>
              {{ photo.created|date:"d.m.Y H:i" }}
            </p>
            {% for tag in photo.tags.all %}
            <a class="tags" href="{% url 'photo:tag' tag.slug %}">#{{ tag.name }}&nbsp;</a>
            {% endfor %}
            {% if user == photo.submitter %}
            <div class="center">
              <div class="btn-group">
                <!-- <a href="{% url 'photo:detail' photo.id %}" class="btn btn-sm btn-outline-primary">Details</a> -->
                <a href="{% url 'photo:update' photo.id %}" class="btn btn-sm btn-outline-success">Update</a>
                <a href="{% url 'photo:delete' photo.id %}" class="btn btn-sm btn-outline-danger">Delete</a>
              </div>
            </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
    {% empty %}
    <h2 class="text-center">There are no photos with the tag {{tag}}!</h2>
    <p class="text-center">Maybe add some?</p>
    <div class="text-center">
      <a href="{% url 'photo:create' %}" class="btn btn-success btn-md">Click here!</a>
    </div>
    {% endfor %}
  </div>
</section>
<br>

{% endblock body %}

picapp/templates/picapp/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
<div class="forms col-md-6 offset-md-3">
  <div class="mx-auto">
    <h1 class="mt-3 text-center">Edit photo {{photo}}</h1>
  </div>
  <div class="form-group">
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.title|as_crispy_field}}<br>
      {{ form.description|as_crispy_field}}<br>
      {{ form.tags|as_crispy_field}}<br>
      {{ form.album|as_crispy_field}}<br>
      <button type="submit" class="btn btn-success">Edit Photo</button>
    </form>
  </div>
</div>
{% endblock body %}

picapp/templates/picapp/update_album.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
<div class="forms col-md-6 offset-md-3">
  <div class="mx-auto">
    <h1 class="mt-3 text-center">Edit {{album}}</h1>
  </div>
  <div class="form-group">
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.title|as_crispy_field}}<br>
      {{ form.description|as_crispy_field}}<br>
      {{ form.thumb|as_crispy_field}}<br>
      {{ form.is_public|as_crispy_field}}<br>
      <button type="submit" class="btn btn-success my-3">Edit album</button>
    </form>
  </div>
</div>
{% endblock body %}